{
 "title": "Quality",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organisation",
    "label": "Organisation",
    "query": "SELECT\n  o.name as \"Name\"\nFROM organisation o\nINNER JOIN contract c on c.organisation_id = o.id\nWHERE c.start_time < $__timeTo() \n  AND (c.stop_time IS NULL OR c.stop_time > $__timeFrom())\nGROUP BY o.name"
   },
   {
    "name": "services",
    "label": "Service",
    "query": "SELECT\n  s.name as \"name\"\nFROM service s\nINNER JOIN contract c on s.contract_id = c.id\nINNER JOIN organisation o on o.id = c.organisation_id\nWHERE c.start_time < $__timeTo() \n  AND (c.stop_time IS NULL OR c.stop_time > $__timeFrom())\n  AND o.name LIKE '$organisation'\n  AND s.service_type = 'HOSTING'"
   }
  ]
 },
 "panels": [
  {
   "title": "Coverage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(s.time, '5m') as \"Time\",\n  avg(s.value) as \"Value\"\nFROM sensor_data s\nINNER JOIN service sv on s.service_id = sv.id\nWHERE s.sensor_name = 'SONAR_COVERAGE'\n  AND $__timeFilter(time)\n  AND sv.name IN ($services)\nGROUP BY \"Time\""
    }
   ]
  },
  {
   "title": "LOC",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(s.time, '5m') as \"Time\",\n  avg(s.value) as \"Value\"\nFROM sensor_data s\nINNER JOIN service sv on s.service_id = sv.id\nWHERE s.sensor_name = 'SONAR_LOC'\n  AND $__timeFilter(time)\n  AND sv.name IN ($services)\nGROUP BY \"Time\""
    }
   ]
  },
  {
   "title": "Score",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(s.time, '5m') as \"Time\",\n  avg(s.value) as \"Value\"\nFROM sensor_data s\nINNER JOIN service sv on s.service_id = sv.id\nWHERE s.sensor_name = 'SONAR_SCORE'\n  AND $__timeFilter(time)\n  AND sv.name IN ($services)\nGROUP BY \"Time\""
    }
   ]
  }
 ]
}